### ISSUE TITLE
Key issue in React

### ISSUE THREAD

**Issue by hydrogen602Trinity** [mmendio2/deepcutsapp#2]
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SearchBar`. See https://reactjs.org/link/warning-keys for more information.
    at LinkWithRef (http://localhost:3000/deepcutsapp/static/js/bundle.js:50446:5)
    at SearchBar (http://localhost:3000/deepcutsapp/static/js/bundle.js:178:5)
    at div
    at Home
    at Routes (http://localhost:3000/deepcutsapp/static/js/bundle.js:51602:5)
    at div
    at div
    at Router (http://localhost:3000/deepcutsapp/static/js/bundle.js:51535:15)
    at BrowserRouter (http://localhost:3000/deepcutsapp/static/js/bundle.js:50344:5)
    at App
```

**Comment by fleckerbr** [comment]
Issue fixed in SearchBar component update (6f31fd25a70442faec56c6daccc9d467988243c6)
